name: release

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    - name: Build package for Release.
      run: |
        cd src/
        dotnet pack -c Release
      if: github.event.action == 'published'
    - name: Push package to nuget.
      run: dotnet nuget push **/SmartHead.Essentials.*.nupkg --source "github"
      if: github.event.action == 'published'
